/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 3d-portfolio\public\models\optimized-room.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Room(props) {
  const { nodes, materials } = useGLTF('/models/optimized-room.glb')
  return (
    <group {...props} dispose={null} scale={1.55} position={[0,-1.75,0]}>
      <group position={[0.011, 3.386, 1.88]} rotation={[-Math.PI / 2, 0, 0]} scale={2.034}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Object_10.geometry} material={materials['Frame.002']} />
          <mesh geometry={nodes.Object_16.geometry} material={materials['Frame.003']} />
          <mesh geometry={nodes.Object_13.geometry} material={materials['Handles.001']} />
        </group>
      </group>
      <mesh geometry={nodes.avaturn_body.geometry} material={materials['avaturn_body_material.001']} position={[-0.002, -39.831, -0.304]} scale={24.677} />
      <mesh geometry={nodes.avaturn_hair_0.geometry} material={materials['avaturn_hair_0_material.001']} position={[-0.002, -39.831, -0.304]} scale={24.677} />
    </group>
  )
}

useGLTF.preload('/models/optimized-room.glb')
